#!/usr/bin/env python3
"""Apply OpenCV calibration result to line_follow_params.json.

This script updates:
- camera.hfov_deg
- camera.vfov_deg
and stores calibration metadata under camera.calibration.
"""

from __future__ import annotations

import argparse
import json
import os
from datetime import datetime


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Apply camera calibration to line_follow_params.json")
    parser.add_argument(
        "--calib-json",
        default="generated/camera_calibration_result.json",
        help="Calibration JSON generated by calibrate_camera_opencv.py",
    )
    parser.add_argument(
        "--params-json",
        default="line_follow_params.json",
        help="Target params JSON",
    )
    return parser.parse_args()


def ensure_parent(path: str) -> None:
    parent = os.path.dirname(path)
    if parent:
        os.makedirs(parent, exist_ok=True)


def main() -> int:
    args = parse_args()

    with open(args.calib_json, "r", encoding="utf-8") as f:
        calib = json.load(f)

    with open(args.params_json, "r", encoding="utf-8") as f:
        params = json.load(f)

    fov = calib["calibration"]["fov_deg"]
    intr = calib["calibration"]["intrinsics"]
    dist = calib["calibration"]["dist_coeffs"]

    params.setdefault("camera", {})
    params["camera"]["hfov_deg"] = float(fov["hfov"])
    params["camera"]["vfov_deg"] = float(fov["vfov"])

    params["camera"]["calibration"] = {
        "applied_at": datetime.now().isoformat(timespec="seconds"),
        "source": args.calib_json,
        "image_size": calib.get("image_size", {}),
        "fx": float(intr["fx"]),
        "fy": float(intr["fy"]),
        "cx": float(intr["cx"]),
        "cy": float(intr["cy"]),
        "dist_coeffs": [float(x) for x in dist],
        "rms_reprojection_error": float(calib["calibration"]["rms_reprojection_error"]),
        "mean_reprojection_error": float(calib["calibration"]["mean_reprojection_error"]),
    }

    ensure_parent(args.params_json)
    with open(args.params_json, "w", encoding="utf-8") as f:
        json.dump(params, f, indent=2, ensure_ascii=False)

    print("[OK] Updated", args.params_json)
    print("  - camera.hfov_deg =", params["camera"]["hfov_deg"])
    print("  - camera.vfov_deg =", params["camera"]["vfov_deg"])
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
